<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCJDZwAH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCJDZwAH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCJDZwAH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCJDZwAH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCJDZwAH\App_KernelDevDebugContainer([
    'container.build_hash' => 'CJDZwAH',
    'container.build_id' => 'be39a8fb',
    'container.build_time' => 1653822336,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCJDZwAH');
